#
# RI (using MySQL) + Callback + MySQL 8.0
#
version: "3.7"

services:
  #
  # Hack9 Reference Implementation
  #
  hack9-ri:
    image: "levi9/hack9-ri:latest"
    command:
      - "--spring.profiles.active=db-mysql"
      - "--spring.datasource.url=jdbc:mysql://mysql/hack9db"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: on-failure
     
  # 
  # Callback handler for invoices
  #
  hack9-callback:
    image: "levi9/hack9-callback:latest"
    depends_on:
      - hack9-ri   
  
  #  
  # MySQL 8.0 RDBMS
  #
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rooted_haxxor
      MYSQL_DATABASE: hack9db
      MYSQL_USER: hack9
      MYSQL_PASSWORD: haxx0r
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "--user=hack9", "--password=haxx0r", "--execute \"SHOW DATABASES;\""]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    