management:
  endpoint:
    info:
      enabled: true
    mappings:
      enabled: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - info
        - mappings
       
spring:
  jackson:
    deserialization:
      use-big-decimal-for-floats: true
      use-big-integer-for-ints: false
 
hack9:
  configuration:
    csv: "classpath:Codes.csv"
    
---

spring:
  profiles: db-postgres
  datasource:
    url: "jdbc:postgresql://localhost/hack9db"
    username: hack9
    password: haxx0r
    initialization-mode: always
    platform: pgsql
    
---

spring:
  profiles: db-h2
  datasource:
    url: jdbc:h2:mem:test_mem
    username: sa
    password: ""
    initialization-mode: ALWAYS
    platform: h2
  h2:
    console:
      enabled: true
      path: "/h2-console"
      
---

spring:
  profiles: db-mysql
  datasource:
    url: "jdbc:mysql://localhost/hack9db"
    username: hack9
    password: haxx0r
    initialization-mode: always
    platform: mysql