management:
  endpoint:
    info:
      enabled: true
    mappings:
      enabled: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - info
        - mappings
        
hack9:
  configuration:
    csv: "src/main/resources/prices.csv"